@url = http://localhost:3000/api/user/deposits


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmYjE1NTc0ZTk4YjhmZDY3ZTYxZiIsImlhdCI6MTY1MDEzNDM4MSwiZXhwIjoxNjUwMTM0NDY3fQ.UKSqQp23iqiixjWAT4hn0VPEF3eU7bx9eWEecgYkSBw

@id = 624ada20e454ce3233c077eb

### Get deposit
GET {{url}}
auth: {{token}}


### Set Deposit to User
POST {{url}}/set/{{id}}
auth: {{token}}
