@url = http://localhost:3000/api
@haas = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDZlNjVjZDI4ZTU5Mjk2ZWI4MjNjOSIsImlhdCI6MTY0OTA3MzAyMCwiZXhwIjoxNjQ5MDczMTA2fQ.ImLEJu5EHr3fJUcHyqPt5kSXm9nji2N5ufPRnl1G4Rg
@frei = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGFkYWYwZTQ1NGNlMzIzM2MwNzdmYSIsImlhdCI6MTY0OTA3Mjk1MCwiZXhwIjoxNjQ5MDczMDM2fQ.EJOTuPd9oAxcsSQTZ_lR1bwQgD4DJGc9GszTF_JHGqY
@id = sdfskldfjsdf

### Login haas
POST {{url}}/auth/login
Content-Type: application/json

{
    "username":"jhaas",
    "password":"123456",
    "key":"WNQKBUPX"
}

### Login frei
POST {{url}}/auth/login
Content-Type: application/json

{
    "username":"afrei",
    "password":"123456",
    "key":"3UCRIDN2"
}




### Set Deposit to User
POST {{url}}/user/selected/deposit/{{id}}
auth: {{haas}}
