@url = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTM2MDlkYWE4ZjI4YmVmMzhiNWFhMSIsImRlcG9zaXRJZCI6IjYyNTM2MDhmYWE4ZjI4YmVmMzhiNWE5ZCIsImlhdCI6MTY1MDEyODEzOSwiZXhwIjoxNjUwMTI4MjI1fQ.Nl5vTOb9evOK-S5WQp9VMtmXlT8qR5Xd7iEu7u_ponQ
@id = sdfskldfjsdf


### Login frei
POST {{url}}/login
Content-Type: application/json

{
    "username":"adanfrei",
    "password":"123456",
    "key":"Q5WPH45J"
}


### Set Deposit to User
POST {{url}}/user/selected/deposit/{{id}}
auth: {{token}}


### Set Deposit to User
GET {{url}}/user/home
auth: {{token}}


