@url = http://localhost:3000/api/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmYjE1NTc0ZTk4YjhmZDY3ZTYxZiIsImRlcG9zaXRJZCI6IjYyNWFmYTc5NTc0ZTk4YjhmZDY3ZTVlYiIsImlhdCI6MTY1MDEzNzcwNCwiZXhwIjoxNjUwMTM3NzkwfQ.-Ivqpu-l2IAWTlz5P4tUNYoaxaXk606QN4ns2w8k_B4
@depositId = 625afa79574e98b8fd67e5eb


### Get Home
GET {{url}}/home
auth: {{token}}


### Get user deposits
GET {{url}}/deposits
auth: {{token}}

### Get user cashes
GET {{url}}/cashes
auth: {{token}}

### Set depositId
PUT {{url}}/set/deposit/{{depositId}}
auth: {{token}}
