@url = http://localhost:3000/api/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGFkYWYwZTQ1NGNlMzIzM2MwNzdmYSIsImRlcG9zaXRJZCI6IjYyNGFkYTIwZTQ1NGNlMzIzM2MwNzdlYiIsImlhdCI6MTY0OTM1NjQwNywiZXhwIjoxNjQ5MzU2NDkzfQ.344x6lzV_zFIrHeljvDQsqehzcSfb535wzpzj0lFrmI
@depositId = 6246064423906053be4fb640

### Get user deposits
GET {{url}}/deposits
auth: {{token}}

### Get user cashes
GET {{url}}/cashes
auth: {{token}}

### Set depositId
POST {{url}}/set/deposit/{{depositId}}
auth: {{token}}
