@url = http://localhost:3000/admin/cashbox
#FREI
@frei = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzc0MjdjZjViZGFiOGI5YTc3NTk5NiIsImtleSI6IkhPTVpBSCIsImlhdCI6MTY0Nzc5NjI4OCwiZXhwIjoxNjQ3Nzk2Mzc0fQ.bZ3_oTUfTkY0w3rf6LFQ8HvhMmMSmCAV27xLT7SmXCE
@haas = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzc4YjJhN2QwYjAwMzUxYTUyNWQyNCIsImtleSI6IjBUVlNFUSIsImlhdCI6MTY0NzgwNzM4OCwiZXhwIjoxNjQ3ODA3NDc0fQ.mCbnd4puE5JuyoEMTfE7mj-hCTcJ1uBedYd6bnoiszs
@id = 6239da7d0558835b42814f53

### Listar todos
GET {{url}}
Authorization: {{haas}}

### Buscar por ID
GET {{url}}/{{id}}
Authorization: {{haas}}


### Crear
POST {{url}}
Authorization: {{haas}}
Content-Type: application/json

{
    "name":"CAJA-CHICA",
    "active":true
}

### Borrar
DELETE  {{url}}/{{id}}
Authorization: {{haas}}

### Actualizar
PATCH  {{url}}/{{id}}
Authorization: {{haas}}
Content-Type: application/json

{
    "name":"CAJA-CHICA",
    "active":false
}
