@url = http://localhost:3000/admin/cashes

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmNzM1MmNjNTQ4MzBjNDM3YzM1NCIsImtleSI6IlE1V1BINDVKIiwiaWF0IjoxNjUwMTM0NzY3LCJleHAiOjE2NTAxMzQ4NTN9.Ux-gS7e-vHndrOYH7Khe277w4luzD4QlL2VFzkwE8J8

@id = 6239da7d0558835b42814f53

### Listar todos
GET {{url}}
auth: {{token}}

### Buscar por ID
GET {{url}}/{{id}}
auth: {{token}}


### Crear
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
    "name":"CAJA-CHICA",
    "active":true
}

### Borrar
DELETE  {{url}}/{{id}}
auth: {{token}}

### Actualizar
PATCH  {{url}}/{{id}}
auth: {{token}}
Content-Type: application/json

{
    "name":"CAJA-CHICA",
    "active":false
}
