@url = http://localhost:3000/admin/customers
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmNzM1MmNjNTQ4MzBjNDM3YzM1NCIsImtleSI6IjU3WFhJRUdOIiwiaWF0IjoxNjUwMTI4NzIwLCJleHAiOjE2NTAxMjg4MDZ9.uiZt5UiDpRAwh-7RTPuntLqSS4Qt1vfIgVwjr8RpAdU
@id = 6239da7d0558835b42814f53

### Listar todos
GET {{url}}
auth: {{token}}

### Buscar por ID
GET {{url}}/{{id}}
auth: {{token}}


### Crear
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
    "name":"ANDRES FERI",
    "active":true
}

### Borrar
DELETE  {{url}}/{{id}}
auth: {{token}}

### Actualizar
PATCH  {{url}}/{{id}}
auth: {{token}}
Content-Type: application/json

{
    "name":"CAJA-CHICA",
    "active":false
}
