@url = http://localhost:3000/admin/deposits


@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmNzM1MmNjNTQ4MzBjNDM3YzM1NCIsImtleSI6IjU3WFhJRUdOIiwiaWF0IjoxNjUwMTI4NzIwLCJleHAiOjE2NTAxMjg4MDZ9.uiZt5UiDpRAwh-7RTPuntLqSS4Qt1vfIgVwjr8RpAdU
#FREI

@id = 624ada20e454ce3233c077eb

### Listado de depositos
GET {{url}}
auth: {{token}}

### Deposito
GET {{url}}/{{id}}
auth: {{token}}


### Crear Depostio
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
    "name":"ECO-EMPRESA-GLEW",
    "address":"Ruta 210 Km 36 - Glew",
    "active":true
}


### Borrar deposito
DELETE  {{url}}/{{id}}
auth: {{token}}

### Modificar deposito
PATCH  {{url}}/{{id}}
auth: {{token}}
Content-Type: application/json

{
    "name":"ECO INDUSTRIA",
    "address":"Ruta 210 km 35,5 - Glew",
    "active":false
}
