@url = http://localhost:3000/admin/deposit

#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNDZlZWVjM2EzNjIzYjUxOTkwZmE5NCIsImtleSI6IksyMUo1UzU5IiwiaWF0IjoxNjQ4ODE2MDk1LCJleHAiOjE2NDg4MTYxODF9.qm-EcZ1V40-7OhWczJi2UMg1syuMHsEr5JxYVwOgum4
# HAAS

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGFkNDNiMzhiMGIyYTI1MDEwZjM5ZCIsImtleSI6IjNVQ1JJRE4yIiwiaWF0IjoxNjQ5MDcyNDQyLCJleHAiOjE2NDkwNzI1Mjh9.7jxbarlFR6Ehr2-jSP0iBamjGdbMdOk0vlX9wy9GDFg
#FREI

@id = 624ada20e454ce3233c077eb

### Listado de depositos
GET {{url}}
auth: {{token}}

### Deposito
GET {{url}}/{{id}}
auth: {{token}}


### Crear Depostio
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
    "name":"SANTA-ANA",
    "address":"Ruta 210 Km 36 - Glew",
    "active":true
}


### Borrar deposito
DELETE  {{url}}/{{id}}
auth: {{token}}

### Modificar deposito
PATCH  {{url}}/{{id}}
auth: {{token}}
Content-Type: application/json

{
    "name":"ECO INDUSTRIA",
    "address":"Ruta 210 km 35,5 - Glew",
    "active":false
}
