@url = http://localhost:3000/admin/product
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGFkNDNiMzhiMGIyYTI1MDEwZjM5ZCIsImtleSI6IjNVQ1JJRE4yIiwiaWF0IjoxNjQ5MzU3MDkxLCJleHAiOjE2NDkzNTcxNzd9.GkFBhBehqwA-y8LlX2yUfkDm5dCvH32CinBsw-IML6o
@id = 6239149253aad9176e0e291e

### Listado de Productos
GET {{url}}
auth: {{token}}

### Producto
GET {{url}}/{{id}}
auth: {{token}}


### Crear Producto
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
    "code":"EI005",
    "description":"Aluminio",
    "categoryId":"623a5ef803792b0268ba258c",
    "price": 750.50,
    "active":true
}


### Borrar Producto
DELETE  {{url}}/{{id}}
auth: {{token}}

### Modificar Producto
PATCH  {{url}}/{{id}}
auth: {{token}}
Content-Type: application/json

{
    "username":"ruta210Glew",
    "rol":"user",
    "active":false
}

### Subir archivo CSV
POST {{url}}/upload
auth: {{token}}
