@url = http://localhost:3000/admin/user
@frei = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzc0MjdjZjViZGFiOGI5YTc3NTk5NiIsImtleSI6IkhPTVpBSCIsImlhdCI6MTY0Nzc5NjI4OCwiZXhwIjoxNjQ3Nzk2Mzc0fQ.bZ3_oTUfTkY0w3rf6LFQ8HvhMmMSmCAV27xLT7SmXCE
@haas = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzc4YjJhN2QwYjAwMzUxYTUyNWQyNCIsImtleSI6IjBUVlNFUSIsImlhdCI6MTY0NzgwNzM4OCwiZXhwIjoxNjQ3ODA3NDc0fQ.mCbnd4puE5JuyoEMTfE7mj-hCTcJ1uBedYd6bnoiszs
@id = 62389a57bac914f4de6cb020


### Listado de usurios
GET {{url}}
Authorization: {{haas}}


### Usuario
GET {{url}}/{{id}}
Authorization: {{haas}}


### Crear Usuario
POST {{url}}
Authorization: {{haas}}
Content-Type: application/json

{
    "username":"jpelotas",
    "description":"Juan Pelotas",
    "password":"123456",
    "cashboxs":["62378b2a7d0b00351a525d24"],
    "deposits":["62378b2a7d0b00351a525d24"],
    "rol":"user",
    "active":true
}


### Borrar usuario
DELETE  {{url}}/{{id}}
Authorization: {{frei}}


### Modificar usuario
PATCH  {{url}}/{{id}}
Authorization: {{haas}}
Content-Type: application/json

{
    "username":"ruta210",
    "rol":"user",
    "cashboxs":["6239e3e14601e76c17ab6551"],
    "deposits":["62378b2a7d0b00351a525d24"],
    "active":false
}
