@url = http://localhost:3000/api/buys

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmYjE1NTc0ZTk4YjhmZDY3ZTYxZiIsImRlcG9zaXRJZCI6IjYyNWFmYTc5NTc0ZTk4YjhmZDY3ZTVlYiIsImlhdCI6MTY1MDEzNzcwNCwiZXhwIjoxNjUwMTM3NzkwfQ.-Ivqpu-l2IAWTlz5P4tUNYoaxaXk606QN4ns2w8k_B4


### List buys
GET {{url}}
auth: {{token}}

### Create buy
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
    "date": "2022-04-19",
    "customerId": "625ee625cf848fc379e48acf",
    "products": [
        {
            "productId":"625afab7574e98b8fd67e5f2",
            "quantity": 2,
            "price": 1000,
            "total": 2000
        },
        {
            "productId":"625afab7574e98b8fd67e5f5",
            "quantity": 1.05,
            "price": 950,
            "total": 960.50
        }
    ],
    "total":2950.50,
    "payment":2950.50,
    "rounded":0,
    "isCountable":true
}

