@url = http://localhost:3000/api/sales

@adanfrei = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmYjE1NTc0ZTk4YjhmZDY3ZTYxZiIsImRlcG9zaXRJZCI6IjYyNWFmYTc5NTc0ZTk4YjhmZDY3ZTVlYiIsImlhdCI6MTY1MDMxMTY1OCwiZXhwIjoxNjUwMzExNzQ0fQ.9KYm-HWu1_KhtV7QcrLUSMZBJHVeS5r2F-ijxjVKS6M
@afrei = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWRiYWVjYTlhODkzNGM2ODVhYmU4OSIsImRlcG9zaXRJZCI6IjYyNWFmYTc5NTc0ZTk4YjhmZDY3ZTVlYiIsImlhdCI6MTY1MDMxMTc3OSwiZXhwIjoxNjUwMzExODY1fQ.WaGK2F8APNKFEEDli2dPkmiWT6SLNLP4NNbgjID1A5k

@id = 625efb611be988174b3f0dcc



### Buy delete adan
DELETE {{url}}/{{id}}
auth: {{adanfrei}}

### Buy delete adan
DELETE {{url}}/{{id}}
auth: {{afrei}}

