const products = [
    {code:'EI001', description:'Cobre 1ra',category:'Metal No Ferroso'},
    {code:'EI001', description:'Cobre 1ra',category:'Metal No Ferroso'},
    {code:'EI002',	description:'Cobre 2da',	category:'Metal No Ferroso'},
    {code:'EI003',	description:'Bronce ',	category:'Metal No Ferroso'},
    {code:'EI004',	description:'Bronce Trafilado',	category:'Metal No Ferroso'},
    {code:'EI005',	description:'Estanado',	category:'Metal No Ferroso'},
    {code:'EI006',	description:'Aluminio',	category:'Metal No Ferroso'},
    {code:'EI007',	description:'Aluminio Karter',	category:'Metal No Ferroso'},
    {code:'EI008',	description:'Perfil',	category:'Metal No Ferroso'},
    {code:'EI009',	description:'Plomo',	category:'Metal No Ferroso'},
    {code:'EI010',	description:'Pasta',	category:'Metal No Ferroso'},
    {code:'EI011',	description:'Zinc',	category:'Metal No Ferroso'},
    {code:'EI012',	description:'Latitas',	category:'Metal No Ferroso'},
    {code:'EI013',	description:'Baterias',	category:'Metal No Ferroso'},
    {code:'EI014',	description:'Radiadores',	category:'Metal No Ferroso'},
    {code:'EI015',	description:'Radiador de Aluminio',	category:'Metal No Ferroso'},
    {code:'EI016',	description:'Acero Inoxidable',	category:'Metal No Ferroso'},
    {code:'EI017',	description:'Bochas de Heladera',	category:'Metal No Ferroso'},
    {code:'EI018',	description:'Bateria con Agua',	category:'Metal No Ferroso'},
    {code:'EI019',	description:'Bateria Gel',	category:'Metal No Ferroso'},
    {code:'EI020',	description:'Motores',	category:'Metal No Ferroso'},
    {code:'EI021',	description:'Mixto',	category:'Metal No Ferroso'},
    {code:'EI022',	description:'Carton'},
    {code:'EI023',	description:'Papel Blanco'},
    {code:'EI024',	description:'Diario / Revista'},
    {code:'EI025',	description:'Chatarra',category:'Metal Ferroso'},
    {code:'EI026',	description:'Fundicion',category:'Metal Ferroso'},
    {code:'EI027',	description:'Pet Cristal'},
    {code:'EI028',	description:'Pet Verde'},
    {code:'EI029',	description:'Plastico Duro'},
    {code:'EI030',	description:'Plastico Blando'},	
    {code:'EI031',	description:'Cable sin quemar',	category:'Metal No Ferroso'},
    {code:'EI032',	description:'Escoria cobre',	category:'Metal No Ferroso'},
    {code:'EI033',	description:'Nahilon'},	
    {code:'EI034',	description:'Plastico TV'},	
    {code:'EI035',	description:'radiografia'},	
    {code:'EI036',	description:'Cable aluminio}
]

module.exports = products
    