@url = http://localhost:3000/api/cash/expence

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWFmYjE1NTc0ZTk4YjhmZDY3ZTYxZiIsImRlcG9zaXRJZCI6IjYyNWFmYTc5NTc0ZTk4YjhmZDY3ZTVlYiIsImlhdCI6MTY1MDE0MzY1OSwiZXhwIjoxNjUwMTQzNzQ1fQ.7QCuY_7oiTQ14tC6CEgrOou0TE_xuefZzokdNxIlDGU

### create expence
POST {{url}}
auth: {{token}}
Content-Type: application/json

{
 "date":"2022-04-16",
 "cashId":"625b0f1ca69f23d331321668",
 "description":"Edesur",
 "costCenter":"Servicios",
 "import":4500
}
