@url = http://localhost:3000/api/products
#Frei
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTM2MDlkYWE4ZjI4YmVmMzhiNWFhMSIsImlhdCI6MTY0OTYzMzc0MiwiZXhwIjoxNjQ5NjMzODI4fQ.ZvvMUjP-e9GcFgHn4Sd-1onHMfYRSAkqRQSEtgGbLuo
@id = 

### Listado de productos
GET {{url}}
auth: {{token}}



